### Pooling is use to reduce the size of features.
### Pooling is used to increase the speed of computation.
### To detect a feature in more robust way (sort of taking out the dominant pixels)

### Pooling are of two types:-  
### max poooling - maximim of the pixel is extracted 
### mean pooling- this is used when we want to take the mean of all the pixels we have in the filter space.
### Pooling has NO PARAMETERS to learn and has only hyper-paramters to tune so nothing can be done using Gradiant Descent. 
### Once we fixed f & s it is just a fixed computation.
### If the image is colored then the same operation is performed on all the channels.
### Max Pooling is most widely used 
### padding is rarely used with pooling.
### f=2 & s=2 is the most used value of these hyper parameters from several research papers.

In [1]:
import numpy as np 
from keras.models import Sequential 
from keras.layers import MaxPooling2D 

In [2]:
# define input image 
image = np.array([[2, 2, 7, 3], 
                  [9, 4, 6, 1], 
                  [8, 5, 2, 4], 
                  [3, 1, 2, 6]]) 
image = image.reshape(1, 4, 4, 1) 

In [6]:
# define model containing just a single max pooling layer 
model = Sequential( 
    [MaxPooling2D(pool_size = 2, strides = 1)]) 

In [7]:
# generate pooled output 
output = model.predict(image) 

In [8]:
# print output image 
output = np.squeeze(output) 
print(output) 

[[9 7 7]
 [9 6 6]
 [8 5 6]]
